name: prbcrud
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.1+2
  firebase_analytics: ^6.0.2
  flutter_auth_buttons: ^0.10.0
  firebase_core: ^0.5.0+1
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.4
  cloud_firestore: ^0.14.1+3
  firebase_database: ^4.1.1 
  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
